import LegalLayout, { legalMetadata } from "@/components/LegalLayout";

export const metadata = legalMetadata(
  "Terms of Use",
  "Terms governing your use of Ross AI, an AI-powered contract review proof-of-concept."
);

const LAST_UPDATED = "June 9, 2026";

export default function TermsPage() {
  return (
    <LegalLayout title="Terms of Use" lastUpdated={LAST_UPDATED}>
      <section>
        <h2>1. Agreement</h2>
        <p>
          By accessing or using Ross AI (&quot;the Service&quot;), you agree to
          these Terms of Use. If you do not agree, do not use the Service.
        </p>
      </section>

      <section>
        <h2>2. What Ross AI Is</h2>
        <p>
          Ross AI is a proof-of-concept tool that uses artificial intelligence
          to summarize uploaded contract PDFs and highlight potential
          obligations. The Service is provided for informational and
          educational purposes only.
        </p>
      </section>

      <section>
        <h2>3. Not Legal Advice</h2>
        <p>
          Ross AI does not provide legal advice and is not a law firm. Output
          from the Service is generated by AI and may be incomplete,
          inaccurate, or outdated. You must not rely on any analysis as a
          substitute for advice from a qualified attorney licensed in your
          jurisdiction. Use of the Service does not create an attorney-client
          relationship.
        </p>
      </section>

      <section>
        <h2>4. Your Responsibilities</h2>
        <p>You agree that you will:</p>
        <ul>
          <li>
            Only upload documents you have the right to process and share for
            this purpose
          </li>
          <li>
            Not upload documents containing highly sensitive personal data
            unless you accept the risks described in our Privacy Policy
          </li>
          <li>
            Independently verify all AI-generated output before making
            business or legal decisions
          </li>
          <li>
            Comply with applicable laws, including data protection and
            confidentiality obligations owed to third parties
          </li>
        </ul>
      </section>

      <section>
        <h2>5. Acceptable Use</h2>
        <p>You may not use the Service to:</p>
        <ul>
          <li>Violate any law or third-party rights</li>
          <li>Upload malware or attempt to disrupt the Service</li>
          <li>Reverse engineer or abuse API endpoints</li>
          <li>
            Present AI output as professional legal advice to others without
            appropriate qualifications and disclaimers
          </li>
        </ul>
      </section>

      <section>
        <h2>6. Intellectual Property</h2>
        <p>
          You retain ownership of documents you upload. You grant us a limited
          license to process those documents solely to provide the Service. We
          retain ownership of the Service, its design, and underlying
          technology.
        </p>
      </section>

      <section>
        <h2>7. Disclaimers</h2>
        <p>
          THE SERVICE IS PROVIDED &quot;AS IS&quot; AND &quot;AS AVAILABLE&quot;
          WITHOUT WARRANTIES OF ANY KIND, WHETHER EXPRESS OR IMPLIED,
          INCLUDING MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND
          NON-INFRINGEMENT. WE DO NOT WARRANT THAT OUTPUT WILL BE ACCURATE,
          COMPLETE, OR SUITABLE FOR ANY PURPOSE.
        </p>
      </section>

      <section>
        <h2>8. Limitation of Liability</h2>
        <p>
          TO THE MAXIMUM EXTENT PERMITTED BY LAW, ROSS AI AND ITS OPERATORS
          WILL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL,
          CONSEQUENTIAL, OR PUNITIVE DAMAGES, OR ANY LOSS OF PROFITS, DATA, OR
          GOODWILL, ARISING FROM YOUR USE OF THE SERVICE OR RELIANCE ON ITS
          OUTPUT.
        </p>
      </section>

      <section>
        <h2>9. Changes</h2>
        <p>
          We may update these Terms from time to time. Continued use after
          changes are posted constitutes acceptance of the revised Terms.
        </p>
      </section>

      <section>
        <h2>10. Contact</h2>
        <p>
          Questions about these Terms may be directed to the project
          maintainer via the Ross AI GitHub repository.
        </p>
      </section>
    </LegalLayout>
  );
}
