"use client";

import { useState } from "react";
import Navbar from "@/components/Navbar";
import UploadZone from "@/components/UploadZone";
import ResultsPanel from "@/components/ResultsPanel";
import ErrorModal from "@/components/ErrorModal";
import Footer from "@/components/Footer";

export default function AnalyzePage() {
  const [file, setFile] = useState<File | null>(null);
  const [isStreaming, setIsStreaming] = useState(false);
  const [summaryText, setSummaryText] = useState("");
  const [obligationsText, setObligationsText] = useState("");
  const [hasResult, setHasResult] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const handleAnalyze = async () => {
    if (!file || isStreaming) return;

    setIsStreaming(true);
    setError(null);
    setSummaryText("");
    setObligationsText("");
    setHasResult(false);

    const formData = new FormData();
    formData.append("file", file);

    try {
      const response = await fetch("/api/review", {
        method: "POST",
        body: formData,
      });

      if (!response.ok) {
        const data = await response.json().catch(() => ({}));
        throw new Error(
          data.error || "Analysis failed. Please try again."
        );
      }

      const reader = response.body!.getReader();
      const decoder = new TextDecoder();
      let accumulated = "";

      while (true) {
        const { done, value } = await reader.read();
        if (done) break;

        accumulated += decoder.decode(value, { stream: true });

        const summaryMatch = accumulated.match(
          /\[SUMMARY\]([\s\S]*?)(?=\[OBLIGATIONS\]|$)/
        );
        const obligationsMatch = accumulated.match(
          /\[OBLIGATIONS\]([\s\S]*)$/
        );

        if (summaryMatch) setSummaryText(summaryMatch[1].trimStart());
        if (obligationsMatch)
          setObligationsText(obligationsMatch[1].trimStart());
      }

      setHasResult(true);
    } catch (err) {
      const message =
        err instanceof Error ? err.message : "An unexpected error occurred.";
      setError(message);
    } finally {
      setIsStreaming(false);
    }
  };

  return (
    <div className="min-h-screen bg-ross-offwhite flex flex-col">
      <Navbar variant="dark" />

      <main className="flex-1 pt-16">
        <div className="max-w-6xl mx-auto px-6 py-16">
          {/* Page header */}
          <div className="mb-12">
            <span className="font-sans text-xs font-medium tracking-[0.3em] uppercase text-ross-midgrey">
              Contract Review
            </span>
            <h1 className="font-serif font-light text-ross-black text-4xl md:text-5xl mt-2">
              Analyze your contract.
            </h1>
          </div>

          {/* Two-column layout */}
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-px bg-ross-lightgrey">
            {/* Left: Upload panel */}
            <div className="bg-ross-offwhite p-8 lg:p-12">
              <UploadZone
                onFileSelect={setFile}
                selectedFile={file}
                isStreaming={isStreaming}
                onAnalyze={handleAnalyze}
              />
            </div>

            {/* Right: Results panel */}
            <div className="bg-ross-offwhite p-8 lg:p-12">
              <ResultsPanel
                summaryText={summaryText}
                obligationsText={obligationsText}
                isStreaming={isStreaming}
                hasResult={hasResult}
              />
            </div>
          </div>

          {/* Disclaimer */}
          <p className="font-sans font-light text-ross-midgrey text-xs text-center mt-8">
            Not legal advice. This analysis is generated by AI and should not
            be relied upon as legal counsel.
          </p>
        </div>
      </main>

      <Footer />

      <ErrorModal
        isOpen={!!error}
        message={error ?? ""}
        onClose={() => setError(null)}
      />
    </div>
  );
}
